name = "Data-Assimilation-fpm"
version = "0.1.0"
license = "license"
author = "Jane Doe"
maintainer = "jane.doe@example.com"
copyright = "Copyright 2022, Jane Doe"
[build]
auto-executables = false
auto-tests = false
auto-examples = false
[install]
library = false
[library]
source-dir="src"
[[ executable ]]
name="DA_cycle"
source-dir="app"
main="DA_cycle.f90"
[[ executable ]]
name="test"
source-dir="app"
main="test.f90"
